<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-6">
    <form action="" method="POST" enctype="multipart/form-data" class="border border-primary">
        <div class="row g-3 align-items-center mt-3 ms-3 mb-3">
            <h2>Registracija į kursus</h2>
            <div class="col-auto">
                <label for="inputName" class="col-form-label">Vardas</label>
            </div>
            <div class="col-auto">
                <input name="name" id="inputName" class="form-control" required>
            </div>
            <div class="col-auto">
            </div>
                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        <label for="inputSurname" class="col-form-label">Pavardė</label>
                    </div>
                <div class="col-auto">
                    <input name="surName" id="inputSurname" class="form-control" required>
                </div>
                <div>
                    <div class="form-group col-auto">
                        <label for="exampleFormControlSelect1" class="col-form-label">Miestas</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Vilnius</option>
                            <option>Kaunas</option>
                            <option>Klaipėda</option>
                        </select>
                    </div>
                </div>
                <h2>Programavimo kalba</h2>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="cValue" value="option1" checked>
                    <label name="C++" class="form-check-label" for="C++">
                        C++
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="phpValue" value="option2">
                    <label name="PHP" class="form-check-label" for="PHP">
                        PHP
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="pythonValue" value="option3">
                    <label name="Python" class="form-check-label" for="Python">
                        Python
                    </label>
                </div>
                <h2>Papildoma informacija</h2>
                <div class="form-floating col-6">
                    <textarea name="info" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                    <label name="info" for="floatingTextarea2">Pvz.: turite C++ programavimo patirties</label>
                </div>
                <div>
                    <input type="file" name="some-file-name" />
                </div>
                <div class="col-6">
                    <button class="btn btn-primary" type="submit" name="Submit">Siųsti</button>
                </div>
            </div>

    </form>
        </div>
    </div>
    <div class="col-6">
        <?php
//        require_once 'profile.phtml';
        require_once 'upload.php';
        ?>
    </div>
</div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>
</html>