<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>
<body>
<div class="container mt-5">
    <div>
        <?php if (isset($downloadFilePath)): ?>
            <img src="<?php echo $downloadFilePath; ?>" class="img-thumbnail img-fluid" style="width: 150px; height: 150px;">
        <?php endif; ?>
    </div>
    <?php echo isset($_POST["name"]) ? $_POST["name"] : "";?><br>
    <?php echo isset($_POST["surName"]) ? $_POST["surName"] : "";?><br>
    <!--        --><?php //echo isset($_POST["city"]) ? $_POST["city"] : "";?>
    <?php echo isset($_POST["C++"]) ? $_POST["C++"] : "C++";?><br>
    <?php echo isset($_POST["PHP"]) ? $_POST["PHP"] : "PHP";?><br>
    <?php echo isset($_POST["Python"]) ? $_POST["Python"] : "Python";?><br>
    <?php echo isset($_POST["info"]) ? $_POST["info"] : "";?>
    <?php
    if (isset($_POST['Submit'])) {
        header('Content-type: image/jpeg');
        $text = $_GET['text'] ?? 'Hello World';

        $image = imageCreate(300, 75);

        $color = imageColorAllocate($image, 200, 200, 200);
        $colorBlue = imageColorAllocate($image, 0, 0, 255);

        imageString($image, 2, 10, 30, $text, $colorBlue);


        imageJpeg($image);

        imageDestroy($image);
    }
    ?>
</body>
</html>
